trigger:
- main   # or your branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  aws_server: "ec2-user@<54.144.2.158>"   # replace with your server user and IP
  target_dir: "/var/www/html"               # folder on AWS Ubuntu server

steps:
- task: DownloadSecureFile@1
  name: sshKey
  inputs:
    secureFile: 'Team04.ppk'   # uploaded in Azure DevOps > Pipelines > Library > Secure files

- script: |
    mkdir -p ~/.ssh
    cp $(sshKey.secureFilePath) ~/.ssh/Team04.ppk
    chmod 600 ~/.ssh/Team04.ppk
    echo "Transferring files..."
    scp -o StrictHostKeyChecking=no -i ~/.ssh/Team04.ppk ./dist/* $(aws_server):$(target_dir)/
  displayName: "Transfer files to AWS Ubuntu server"